stages:
  - build

variables:
  # Customize these variables as needed
  NODE_IMAGE: "node:21"

before_script:
  - apt-get update -qy
  - apt-get install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_21.x | bash -
  - apt-get install -y nodejs
  - curl -fsSL https://get.pnpm.io/install.sh | sh -

build:
  tags:
    - build
  stage: build
  script:
    - pnpm install
    - pnpm build:prod
  artifacts:
    paths:
      - dist/

